### ISSUE TITLE
Doesn't translate attributes that are also cast as array

### ISSUE THREAD

**Issue by yuters** [spatie/laravel-translatable#115]
I have a column with a dynamic json structure that I want to translate. The package works great for retrieving that structure, ex.: `{"en":{"key":"value"}}` but ignores the translation when saving it, so it just saves `{"key":"value"}`.

Here is the part where the problem is, arrays are skipped when setting a translatable attribute:
https://github.com/spatie/laravel-translatable/blob/master/src/HasTranslations.php#L35-L38

I'm guessing that it's preventing some other bug but I'm not sure what.

**Comment by freekmurze** [comment]
The intended use of this package is to just translate strings. There's no support for automatically casting translated values. Because we don't have a need for this in our own projects, I'm not going to invest time in it.

But if the solution is simple I'd accept a PR with tests that adds this to the package.

**Comment by yuters** [comment]
Removing the `is_array` check was problematic when saving an array of translations. I would have liked to create a PR for this but the simplest solution I found is actually outside of this package.

For anyone stumbling here, using a `set{CastsProperty}Attribute` on your model and recreating the translation array inside that method,  then setting the attribute with `json_encode` will work fine.

**Comment by jsphpl** [comment]
@yuters thanks for the workaround! Unfortunately, your solution breaks with v3, where `getTranslation()` got a return type hint of `string`.

**Comment by promatik** [comment]
With v2 I used to have a fake field `extras`, and another fake field `extras_translatable`, which was translatable.
v3 breaks this because of the `getTranslation(): string`, by creating a trait which overrides the function and removing the `: string` I was able to get everything working again.

@freekmurze is it possible to remove the return as `string` from the function? This would allow fake fields to be translatable.
