### ISSUE TITLE
Add prioritized fallbacks for different languages

### ISSUE THREAD

**Issue by sdcinglis** [spatie/laravel-translatable#138]
The single fallback locale isn't ideal for many situations, for instance if my app includes Castillian and Latin American dialects of Spanish, I will most likely want to fallback to the other before falling back to english. Ideally you could write fallbacks like this:

```
return [
  'fallback_locale' => [
    'es-MX' => ['es-ES', 'en-US'],
    'es-ES' => ['es-MX', 'en-US'],
    'default' => en-US
  ],
];
```

**Comment by sebastiandedeyne** [comment]
I'd rather stay close to Laravel's `fallback_locale` configuration value, which must be a string. (actually, I'm not sure anymore why this package uses it's own config file instead of the value in `config/app.php`)

If you need multiple fallback locales in your app, I suggest you override the `normalizeLocale` method.

https://github.com/spatie/laravel-translatable/blob/3d883ca46bdd6d55fb1ffffa7ff7d37ba23d3a89/src/HasTranslations.php#L150
