### ISSUE TITLE
setAttribute has not been applied, because there are collisions with other trait methods 

### ISSUE THREAD

**Issue by cord** [spatie/laravel-translatable#156]
am trying to use this nice package within nova in combination rinvex/laravel-attributes.

However combining both traits in the model 

```
class myModel extends Model {

    use \Rinvex\Attributes\Traits\Attributable;
    use \Spatie\Translatable\HasTranslations;

}
```

causes the error

**Trait method setAttribute has not been applied, because there are collisions with other trait methods**

Is there any way to work around this situation?

See [laravel-attributes/issues/80](https://github.com/rinvex/laravel-attributes/issues/80)

**Comment by freekmurze** [comment]
I'm not a user of laravel-attributes. So I'm not going to look into this. If there is something that our package can do to fix this is a non breaking way, please submit a PR.

**Comment by markjaquith** [comment]
I encountered this myself, when using `BenSampo\Enum\Traits\CastsEnums` along with my own trait that defined `setAttribute()`.

If you actually don't want to use `setAttribute()` from one of the traits, you can use `insteadof` to indicate that. Or, in my case, I wanted to use both of them. So I just made a third trait, that aliased `setAttribute()` in each of the other traits, added its own `setAttribute()` (the only one that the Model will see), and had that `setAttribute()` call `setAttribute()` on both of the "sub-traits", before calling the parent `setAttribute()`.

```php
<?php

namespace App\Traits;

use BenSampo\Enum\Traits\CastsEnums;
use App\Traits\HasDeepLinks;

trait CastsEnumsAndHasDeepLinks {
	// We have to do this because we're importing two traits that define setAttribute().
	use CastsEnums, HasDeepLinks {
		CastsEnums::setAttribute as enumSetAttribute;
		HasDeepLinks::setAttribute as deepLinksSetAttribute;
	}

	/**
	 * Set a given attribute on the model.
	 * We have to do this because we're importing two traits that define setAttribute().
	 *
	 * @param  string  $key
	 * @param  mixed  $value
	 * @return $this
	 */
	public function setAttribute($key, $value) {
		$this->enumSetAttribute($key, $value);
		$this->deepLinksSetAttribute($key, $value);
		return parent::setAttribute($key, $value);
	}
}
```

Things will probably get weird if both `setAttribute()` calls are modifiying the same attribute, because each will be passed the original `$value`. Additional work would have to be done to chain the `$value` through them. (Maybe by looking at the current `$this->$key` and seeing if it changes after each trait does its thing?)

**Comment by daniel-agprop** [comment]
I am aware that this issue is pretty old but my problem is directly related to this, regarding the fact that I am not using `laravel-attributes` instead I am using `laravel-enums`. 

If I try to use both packages inside the same model, like this:
```
class MyModel extends Model {

    use Spatie\Translatable\HasTranslations;
    use Spatie\Enum\Laravel\HasEnums;

}
```
I get the same error as mentioned in the original issue:
`Trait method 'setAttribute' will not be applied, because it collides with 'HasTranslations'`

I already tried the workaround provided by @markjaquith but without any success.

Maybe this issue affects the compatibility between your other packages as well.  
I would really appreciate being able to use both packages in the same model.

Maybe you guys have an idea?
Keep on doing the great work!

**Comment by Dathix** [comment]
I am aware that this issue is pretty old but my problem is directly related to this, regarding the fact that I am not using `laravel-attributes` instead I am using `laravel-enums`.

If I try to use both packages inside the same model, like this:

```
class MyModel extends Model {

    use Spatie\Translatable\HasTranslations;
    use Spatie\Enum\Laravel\HasEnums;

}
```

I get the same error as mentioned in the original issue:
`Trait method 'setAttribute' will not be applied, because it collides with 'HasTranslations'`

I already tried the workaround provided by @markjaquith but without any success.

Maybe this issue affects the compatibility between your other packages as well.
I would really appreciate being able to use both packages in the same model.

Maybe you guys have an idea?
Keep on doing the great work!

**Comment by markjaquith** [comment]
@Dathix What does your "trait bridge" look like, and how is it failing?

**Comment by Dathix** [comment]
The error I was getting after adding my trait was not related to the trait itself.
In fact @markjaquith, your workaround works flawlessly! Thanks again!

I was getting this error if I tried to migrate and seed my database with my modified factory, adding the field for the enum:

`array_filter() expects parameter 1 to be array, string given` in `HasTranslations.php:70`

After a quick search on this, I found this comment with the solution to my problem:
https://github.com/spatie/laravel-translatable/issues/51#issuecomment-306033819

Now I am just curious why I now have to modify my factory as mentioned in the comment after adding the `HasEnum` trait when everything was working before. 

I thought that the model was using a locale from the config during seeding but this seems to be wrong. 

Anyway, maybe someone from @spatie can clarify this once and forever.

**Comment by Dathix** [comment]
Unfortunately, I had been pleased way too early. Sorry about that!

Everything I mentioned above actually solved my problem with the seeding but I get the same error message when I try to access any view that is using the model. 

Not really sure about the changes I did, because after modifying the factory as mentioned above the slug is no longer translated. I also use `HasSlug` on the model, so maybe it is related to that. 

So here is my trait, incase I did something wrong there:
```
trait HasEnumAndTranslations
{
    use HasTranslations, HasEnums {
        HasTranslations::setAttribute as setAttributeTranslations;
        HasEnums::setAttribute as setAttributeEnum;
    }

    public function setAttribute($key, $value)
    {
        $this->setAttributeTranslations($key, $value);
        $this->setAttributeEnum($key, $value);
        return parent::setAttribute($key, $value);
    }
}
```

I am starting to get really confused, so I hope someone can help me out.

**Comment by markjaquith** [comment]
`HasSlug` doesn't provide `setAttribute()`, so that's fine.

Did you update your models to use `HasEnumAndTranslations` instead of the `HasEnums` and `HasTranslations`?

**Comment by Dathix** [comment]
Yes I did that.

**Comment by Dathix** [comment]
I reverted all the changes I did and started all over again.

After some additional debugging I changed the trait as follows:

```
trait HasEnumAndTranslations
{
    use HasTranslations, HasEnums;

    public function setAttribute($key, $value)
    {
        if ($this->isEnumAttribute($key)) {
            $this->setEnumAttribute($key, $value);
        }

        if ($this->isTranslatableAttribute($key)) {
            return $this->setTranslation($key, $this->getLocale(), $value);
        }

        return parent::setAttribute($key, $value);
    }
}
```

Everything seems to work now.
