### ISSUE TITLE
extend getTranslation with bool withFallback

### ISSUE THREAD

**Issue by meta0102** [spatie/laravel-translatable#26]
Is it possible to extend the “getTranslation” with bool withFallback like this package? https://github.com/dimsav/laravel-translatable/blob/master/src/Translatable/Translatable.php
 
e.g
public function getTranslation(string $attributeName, string $locale, bool withFallback) : string

thanks

**Comment by freekmurze** [comment]
I'd accept a fully tested PR that adds this to the package.

**Comment by miclf** [comment]
Hey, I’m just passing by :-)

If someone makes a PR for this, I would suggest also adding a `getTranslationWithFallback()` method or something similar. This method would simply “proxy” to `getTranslation()` and call it with the `$withFallback` parameter to true.

We can see this kind of things in many places in Laravel (for example [in the query builder](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Query/Builder.php#L593-L596)), because they usually try to avoid exposing booleans directly in method signatures. So they make additional “proxy” methods to make the use of these booleans easier and more readable.

Just my two cents!

**Comment by freekmurze** [comment]
@miclf good idea

**Comment by meta0102** [comment]
I'll try to make my first PR ;) including getTranslationWithFallback

Should i also make a method for getTranslationWithoutFallback?
