### ISSUE TITLE
isTranslated

### ISSUE THREAD

**Issue by aurawindsurfing** [spatie/laravel-translatable#97]
At first that you for the amazing package! I have faced one issue that might be useful for some people. Once implementing existing data I had to check if the model was already translated and if not then to perform the translation. A method isTranslated returning bool would be a really handy addition.

Thank you!

PS. My code doing the same thing is not pretty therefore no pull request ;-)

**Comment by freekmurze** [comment]
You can add such a function to your own model.

**Comment by Grunkhead** [comment]
A good way to solve this problem is by creating a helper. In this helper you will create the following function;

![image](https://user-images.githubusercontent.com/746279/62138287-b37cc980-b2e7-11e9-86d4-330c6c8d8706.png)

This way it automatically checks all the fields in your translatable array on your model. You have to change the array from 'protected' to 'public', otherwise the array is not reachable.

The second parameter allows you to add specific translatable field names, those fields will be ignored.

Then you can create for example in Laravel Nova. A boolean field which shows a red or green color to represent if it is translated or not.

![image](https://user-images.githubusercontent.com/746279/62138535-12424300-b2e8-11e9-98ac-c21acc8a1178.png)

**In my opinion this is a good feature to have. Especially for the 'Laravel Nova translatable' package.** Otherwise you have to go to the show view, to check if it translated.
